//Scene textures
LTexture gDotTexture;
LTexture gPaddleTexture;
LTexture gBricksTextureBlue;
LTexture gBricksTextureRed;
LTexture gBricksTextureGreen;
LTexture gBricksTexturDearkgreen;
LTexture gBricksTextureIndigo;
LTexture gBricksTextureOrange;
LTexture gBricksTexturePink;
LTexture gBricksTextureSolid;
LTexture gBricksTextureViolet;
LTexture gBricksTextureYellow;
//Rendered texture
LTexture gTextTexture;

//Scene textures
LTexture gFPSTextTexture;
LTexture gGameOverTexture;
LTexture gGameWin;
LTexture ghigh_Score;
LTexture gBgTexture;
LTexture gBgTexturelv2;
LTexture gBg_Mainmenu;
LTexture gAbout[10];
LTexture gBgLv1;
LTexture gTextbox;